import { FC } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";

const Slider: FC = () => {
  return (
    <div className="h-vh-75 border">
      <div className="flex flex-col h-full">
        <div className="">
          <Image
            src="https://cartzilla.createx.studio/img/home/hero-slider/05.jpg"
            alt=""
            width="420"
            height="430"
            layout="responsive"
          />
        </div>
        <div className="flex flex-col flex-1 items-center justify-start gap-3 ">
          <h1 className="text-2xl font-light  mt-4">World of music with</h1>
          <h1 className="text-4xl font-medium text-gray-700">Headphones</h1>
          <h3 className="text-xl font-light">Choose between top brands</h3>
          <button className="bg-primary py-2 px-6 text-white rounded-md mt-3">
            Shop Now
          </button>
        </div>
        <div className="self-center">...</div>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <div className="w-screen">
      <Head>
        <title>CartZilla | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <header className="flex flex-col bg-lightBlue ">
          <Slider />
          <div>Tiles</div>
        </header>
      </Layout>
    </div>
  );
};

export default Home;
